services:
      web-server:
              build:
                context: .
                dockerfile: nginx/Dockerfile
              depends_on:
                - php
              ports:
                - 5170:80
              volumes:
                  - ./src:/var/www/html/
                  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                
              networks:
                - internal

      php:
        image: php:8.1-fpm-alpine
        networks:
            - internal
        volumes:
        - ./src:/var/www/html/

networks:
  internal:
    driver: bridge

